#%RAML 1.0
title: OIMSystemAPI

/accounts:
  get:
    description: Retrieves employee data from OIM
    responses:
      200:
        body:
          application/json:
            example: !include responses/account.json
              
    
